### ISSUE TITLE
Crash on subscribe

### ISSUE THREAD

**Issue by shahimclt** [pwittchen/ReactiveSensors#20]
I just copy pasted the sample code on the Github page into my project :

``` java
    new ReactiveSensors(context).observeSensor(Sensor.TYPE_GYROSCOPE)
        .subscribeOn(Schedulers.computation())
        .filter(ReactiveSensorFilter.filterSensorChanged())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Action1<ReactiveSensorEvent>() {
          @Override public void call(ReactiveSensorEvent reactiveSensorEvent) {
            SensorEvent event = reactiveSensorEvent.getSensorEvent();

            float x = event.values[0];
            float y = event.values[1];
            float z = event.values[2];

            String message = String.format("x = %f, y = %f, z = %f", x, y, z);

            Log.d("gyroscope readings", message);
          }
        });
```

But I get this error :

> FATAL EXCEPTION: main
>  Process: com.qbes.totobusdriver, PID: 4543
>  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
>    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
>    at android.os.Handler.handleCallback(Handler.java:739)
>    at android.os.Handler.dispatchMessage(Handler.java:95)
>    at android.os.Looper.loop(Looper.java:145)
>    at android.app.ActivityThread.main(ActivityThread.java:6117)
>    at java.lang.reflect.Method.invoke(Native Method)
>    at java.lang.reflect.Method.invoke(Method.java:372)
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
>   Caused by: rx.exceptions.OnErrorNotImplementedException
>    at rx.Observable$27.onError(Observable.java:7923)
>    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
>    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
>    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
>    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
>    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
>    at android.os.Handler.handleCallback(Handler.java:739) 
>    at android.os.Handler.dispatchMessage(Handler.java:95) 
>    at android.os.Looper.loop(Looper.java:145) 
>    at android.app.ActivityThread.main(ActivityThread.java:6117) 
>    at java.lang.reflect.Method.invoke(Native Method) 
>    at java.lang.reflect.Method.invoke(Method.java:372) 
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
>   Caused by: rx.exceptions.MissingBackpressureException
>    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:130)
>    at rx.internal.operators.OperatorFilter$1.onNext(OperatorFilter.java:54)
>    at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
>    at com.github.pwittchen.reactivesensors.library.ReactiveSensors$1$1.onSensorChanged(ReactiveSensors.java:110)
>    at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:503)
>    at android.os.MessageQueue.nativePollOnce(Native Method)
>    at android.os.MessageQueue.next(MessageQueue.java:143)
>    at android.os.Looper.loop(Looper.java:130)
>    at android.app.ActivityThread.main(ActivityThread.java:6117) 
>    at java.lang.reflect.Method.invoke(Native Method) 
>    at java.lang.reflect.Method.invoke(Method.java:372) 
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by pwittchen** [comment]
There maybe few sources of this error:
- sensor doesn't exist
- there was some random error
- others

Please, read section about [good practices](https://github.com/pwittchen/ReactiveSensors#good-practices) related to handling sensor events.

You can check if this sensor exists as follows:

``` java
if (reactiveSensors.hasSensor(SENSOR_TYPE)) {
  // observe sensor
} else {
  // show error message
}
```

Moreover, you can handle errors in your app. Documentation shows just basic example without error handling.

You can handle errors with RxJava as follows:

``` java
   new ReactiveSensors(context).observeSensor(Sensor.TYPE_GYROSCOPE)
        .subscribeOn(Schedulers.computation())
        .filter(ReactiveSensorFilter.filterSensorChanged())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Subscriber<ReactiveSensorEvent>() {
          @Override public void onCompleted() {
          }

          @Override public void onError(Throwable e) {
            // handle error here
          }

          @Override public void onNext(final ReactiveSensorEvent event) {
            // handle event here
          }
        );
```

Please, check how app behaves with checking sensor existence and error handling.

**Comment by Githeo** [comment]
Same error, mostly coming at the first start and always with two sensors: BMI160 gyroscope and BMI160 accelerometer.

**Comment by pwittchen** [comment]
@Githeo Have you tried my suggestion mentioned in this issue with `onError()` method?

**Comment by Githeo** [comment]
Sure. That avoids the crash, but since an error occurs on SensorX, no more data is collected from that sensor.

**Comment by pwittchen** [comment]
Then, you can try to use RxJava operators like: `repeat()`, `retryWhen()` or something like that to restart observing sensors. It should be possible and crashes during data processing may happen.

**Comment by pwittchen** [comment]
Nevertheless, thanks for your comments. It's good input to improve documentation and describe mentioned use cases.

**Comment by Githeo** [comment]
Thank you. As you suggested retry() gracefully resubscribes. The only drawback is that I have almost each measure duplicate. Using distinct() or distinctUntilChanged() do not help. 
By the way, if it can helps, the aforementioned issue was more evident adding a specific delay SensorManager.SENSOR_DELAY_FASTEST

**Comment by pwittchen** [comment]
Maybe try to change order of the called methods (replace `distict()` with `retry()`)? In some cases with RxJava it matters (e.g. for subscribing and observing). It's possible that here is a similar issue. Later I'll check it as well.
