### ISSUE TITLE
Fatal exception when the device does not have the sensor

### ISSUE THREAD

**Issue by lucas34** [pwittchen/ReactiveSensors#29]
Hi,

If the device does not have the sensor you are throwing a fatal exception outside the Rx scope. Isn't it better if you put the error to the Rx error stream ? So the client that subscribe can handle the error properly inside the onError callback and all the on Error operator.

I can PR

Regards,
Lucas

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. There is a method `reactiveSensors.hasSensor(SENSOR_TYPE)`, which can be used for checking whether sensor exists. Nevertheless, it can be thrown in onError(...) method of Subscriber as well. It can be subject of future improvement.

Regards,
Piotr

**Comment by pwittchen** [comment]
If you are able to provide the solution for that problem, all PRs are always welcome. :)

**Comment by lucas34** [comment]
We can used the checked exception, what about creating a custom exception inside the library like "SensorNotSoundException". Or maybe a better name ?

**Comment by pwittchen** [comment]
The exception name `SensorNotFoundException` looks fine for me.
You've made a typo in your comment ant typed `Sound` instead of `Found`.

**Comment by lucas34** [comment]
Oh yeah

I update the PR tomorrow

**Comment by pwittchen** [comment]
Great! Thanks. :)

**Comment by pwittchen** [comment]
PR merged, so this issue can be closed.
