### ISSUE TITLE
Observing multiple sensors together

### ISSUE THREAD

**Issue by lookageek** [pwittchen/ReactiveSensors#33]
In this popular [Android docs example](https://developer.android.com/guide/topics/sensors/sensors_position#sensors-pos-orient) of computing device orientation using accelerometer and magnetometer, sensor manager registers to listen to multiple sensors, which seems to be currently not possible in the API of ReactiveSensors. Can you point me if this is possible? I see that code of [ReactiveSensor.observeSensor](https://github.com/pwittchen/ReactiveSensors/blob/RxJava2.x/library/src/main/java/com/github/pwittchen/reactivesensors/library/ReactiveSensors.java#L111) cannot handle it currently. Is there any plans to add the same? Or would you be interested in a PR for this?

**Comment by pwittchen** [comment]
Hi,

Right now, it's not possible with this library, but it can be improved and we can add such option. It sounds like a good idea.

Regards,
Piotr

**Comment by catalinghita8** [comment]
@lookageek you can check #37 PR on this matter. It is functional, yet I would double check it if one might include it in production.
