### ISSUE TITLE
ReactiveSensors not working with Sensor.TYPE_STEP_COUNTER

### ISSUE THREAD

**Issue by arsSomnium** [pwittchen/ReactiveSensors#35]
ReactiveSensors returns does not return ReactiveSensor Event when calling callback.
`.subscribe(new Consumer<ReactiveSensorEvent>() {
                    @Override 
                    public void accept(ReactiveSensorEvent **reactiveSensorEvent**) throws Exception {
                        SensorEvent event = reactiveSensorEvent.getSensorEvent();
                         sendSensorBroadcast(event);
                    }
                }`
reactiveSensorEvent == null!!
Any thoughts regarding that topic?
Beside great lib of yours, love it a lot.

**Comment by pwittchen** [comment]
Hi,

It may be related to the fact that you're receiving both sensors readings and accuracy changes events. If you need sensor readings only, then you should filter these events. It's described in the docs here: https://github.com/pwittchen/ReactiveSensors#letting-it-crash. 

Another option is the fact, that your device does not have step counter sensor. You can verify it according to the description here: https://github.com/pwittchen/ReactiveSensors#checking-whether-sensor-exists.

Regards,
Piotr

**Comment by pwittchen** [comment]
There's no reply since a few months, so I assume, problem no longer exists.
