### ISSUE TITLE
Handler param should be removed from methods

### ISSUE THREAD

**Issue by piotr-pawlowski** [pwittchen/ReactiveSensors#36]
You should remove handler param from public methods. You have to create handler on your own based on thread execution (Schedulers in subscribeOn method) and then pass it to SensorManager. Right now, I can pass a handler (related to custom HandlerThread) and call subscribeOn (eg. Schedulers.computation()). So replace passing a handler with supporting Schedulers in correct way.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I'll take a look at that.
Moreover, if you have any valid solution in mind, PRs are welcome.

Regards,
Piotr

**Comment by pwittchen** [comment]
I took a look at the code and I think, the use case you described is not a mistake, but wrong library usage, which is hard to prevent in 100% cases. You can create custom `Handler`, then pass it to `SensorManager`, create `HandlerScheduler` with using previously created `Handler` and use it in `subscribeOn(...)` method. It's a library, so it should be flexible.

**Comment by piotr-pawlowski** [comment]
You should get handler from thread declared in subscribeOn method. If I call subscribeOn(Schedulers.computation()) method and do not pass Handler param then SensorEventCallback methods will be invoked in main thread. It's a bug.

Fast solution:

    public void subscribe(ObservableEmitter<SensorEvent> emitter) throws Exception {
        if (Looper.myLooper() == null) { //Null if current thread is not main thread
            Looper.prepare();
            Looper.loop();
        }

        final Handler handler = new Handler();  //Handler related to current thread

        SensorEventListener sensorEventListener = new SensorEventListener() {
            @Override
            public void onSensorChanged(SensorEvent sensorEvent) {
                //Invoked in thread declared in subscrieOn
            }

            @Override
            public void onAccuracyChanged(Sensor sensor, int accuracy) {
               //Invoked in thread declared in subscrieOn
            }
        };

        emitter.setCancellable(() -> {
            sensorManager.unregisterListener(sensorEventListener);
            if (handler.getLooper() != Looper.getMainLooper()) { //Quit thread if is not main thread
                handler.getLooper().quitSafely();
            }
        });

       sensorManager.registerListener(sensorEventListener, sensor, samplingPeriodUs, handler);
    }

**Comment by pwittchen** [comment]
Ok, now it's more clear.

**Comment by piotr-pawlowski** [comment]
Please have a look at SensorManager implementation (line 95): [link](https://android.googlesource.com/platform/frameworks/base/+/0e2d281/core/java/android/hardware/SystemSensorManager.java)

      Looper looper = (handler != null) ? handler.getLooper() : mMainLooper;

So nullable handler causes calling callbacks method in main thread.

**Comment by pwittchen** [comment]
Done.
